services:
  devbox:
    image: node:20
    working_dir: /app
    volumes:
      - .:/app
      - ./logs:/app/logs
    ports:
      - "5173:5173"
    command: >
      sh -c "npm install &&
             mkdir -p logs &&
             npm run dev &
             npm run cssw &
             npm run test &
             wait"
    tty: true
