name: deploy

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  build-deploy:
    name: Builds and releases the site
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - id: 'checkout'
      uses: 'actions/checkout@v3'

    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: ${{ secrets.CREDENTIALS_JSON }}

    - id: 'setup_nodejs'
      run: |-
        sudo apt update && \
          sudo apt install -y nodejs npm

    - id: 'setup_vite'
      run: |-
        npm install

    - name: 'build'
      run: |-
        npm run build

    - id: 'deploy'
      uses: 'google-github-actions/upload-cloud-storage@v1'
      with:
        path: './dist/'
        destination: ${{ secrets.GCS_PREFIX }}
        parent: false
