name: Tests

on:
  push:
    branches: ['*']

  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: 'tests'
  cancel-in-progress: true

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Test
        run: npm run coverage
